-- ============================================================================
-- Migration 002 — Denormalize active join columns onto action_node (no-op)
-- ============================================================================
-- This migration originally added project_name / space_name / space_path to
-- action_node via ALTER TABLE ADD COLUMN. Migration 001 was later updated to
-- include those columns inline in the CREATE TABLE statement, which made
-- this migration's ADD COLUMNs collide on every fresh OPFS bootstrap with
--   SQLite3Error: SQLITE_ERROR: duplicate column name: project_name
-- causing _runMigrations to throw, isSqliteAvailable() to return false, and
-- every read to fall through to REST.
--
-- The fix is to make this migration a no-op. The columns now live in 001;
-- DBs that bootstrapped on the older 001 (without the columns) and recorded
-- this migration's earlier successful run already have the columns. DBs on
-- the newer 001 don't need this migration to do anything.
--
-- Kept as a tracked migration (not deleted) so already-applied DBs stay in
-- sync with the runner's _migrations ledger.
-- ============================================================================

-- intentionally empty
SELECT 1;
